name: test

on:
  workflow_dispatch:
  create:

env:
  srcref: ${{ vars.GITHUB_REF }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo "Ref: $srcref"
